[package]
name = "ejs"
version = "0.1.0"
authors = ["Jaebum Lee <kev0960@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.59"
html-escape = "0.2.9"
